# Generated by Django 3.1.1 on 2020-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('now', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, default='')),
                ('photos', models.ImageField(upload_to='list_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
