# Generated by Django 3.1.1 on 2020-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200905_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uni_code',
            field=models.IntegerField(verbose_name=3349876),
        ),
    ]
